In [1]:
import numpy as np

In [2]:
A = np.array([[50, 0, 10, 20],
             [10, 200, 23, 54],
             [5, 44, 23, 54]])
print(A)

[[ 50   0  10  20]
 [ 10 200  23  54]
 [  5  44  23  54]]


In [4]:
cal = A.sum(axis=0)
print(cal)

[ 65 244  56 128]


In [8]:
A2 = A/cal.reshape(1,4)
print(A2)

[[ 0.76923077  0.          0.17857143  0.15625   ]
 [ 0.15384615  0.81967213  0.41071429  0.421875  ]
 [ 0.07692308  0.18032787  0.41071429  0.421875  ]]


In [13]:
A

array([[ 50,   0,  10,  20],
       [ 10, 200,  23,  54],
       [  5,  44,  23,  54]])